"""alter tables user, wallet, trade for delete

Revision ID: 07b51640bb92
Revises: 9791c51da12f
Create Date: 2025-09-10 12:37:59.958658

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07b51640bb92'
down_revision: Union[str, Sequence[str], None] = '9791c51da12f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('trades_user_id_fkey'), 'trades', type_='foreignkey')
    op.create_foreign_key(None, 'trades', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('wallets_user_id_fkey'), 'wallets', type_='foreignkey')
    op.create_foreign_key(None, 'wallets', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'wallets', type_='foreignkey')
    op.create_foreign_key(op.f('wallets_user_id_fkey'), 'wallets', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'trades', type_='foreignkey')
    op.create_foreign_key(op.f('trades_user_id_fkey'), 'trades', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
