"""cascade delete transactions

Revision ID: 41b33de54811
Revises: 07b51640bb92
Create Date: 2025-09-10 12:46:16.767577

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41b33de54811'
down_revision: Union[str, Sequence[str], None] = '07b51640bb92'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('transactions_wallet_id_fkey'), 'transactions', type_='foreignkey')
    op.create_foreign_key(None, 'transactions', 'wallets', ['wallet_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.create_foreign_key(op.f('transactions_wallet_id_fkey'), 'transactions', 'wallets', ['wallet_id'], ['id'])
    # ### end Alembic commands ###
